name: tests
on:
  # Trigger worfklow when branch or tags are pushed
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
    paths:
      - "lua/**"
      - "plugin/**"
      - "tests/**"
jobs:
  tests:
    name: Run ALL lua tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Run tests
        shell: bash
        run: |
            make -sR -C tests/ all
